[project]
name = "2024"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "bs4>=0.0.2",
  "numpy>=2.1.3",
  "requests>=2.32.3",
  "typer>=0.15.1",
]

[tool.ruff]
# Allow lines to be as long as 120.
line-length = 120
